### ISSUE TITLE
Xcode build fail with error

### ISSUE THREAD

**Issue by byFadili** [allboatsrise/expo-marketingcloudsdk#6]
Hi @andrejpavlovic  !
I am unable to build the App using Xcode after installing `@allboatsrise/expo-marketingcloudsdk` 

## Expected Behavior
Xcode build success

## Actual Behavior
Xcode build throws error after running `npx expo prebuild -p ios`:
`'EXNotifications/EXNotificationCenterDelegate.h' file not found` in `Pods > Development Pods > ExpoMarketingCloudSdk > ExpoMarketingCloudSdk-Bridging-Header.h`

## Steps to Reproduce the Problem

  1. run `npx expo prebuild -p ios`
  2. open project in Xcode > run `Build` command 

## Specifications

  - Dependencies:
    - "expo": "~48.0.15",
    - "expo-notifications": "~0.18.1",
    - "@allboatsrise/expo-marketingcloudsdk": "^48.0.0",
    - "react-native": "0.71.7",
  - Platform: IOS
  - Xcode Version 14.3
  

Thank you in advance for your help !

**Comment by andrejpavlovic** [comment]
My guess is that `expo-notifications` is not added to list of plugins in your `app.config` configuration file. I've updated the README file to include `expo-notifications` plugin in the configuration, but you can read up more on how to configure it in [Expo Notifications documentation](https://github.com/allboatsrise/expo-marketingcloudsdk/blob/6ca9d07555bc31e7fb2b12701bc96eded499d66f/README.md?plain=1#L35).

https://github.com/allboatsrise/expo-marketingcloudsdk/blob/6ca9d07555bc31e7fb2b12701bc96eded499d66f/README.md?plain=1#L27-L36

**Comment by byFadili** [comment]
@andrejpavlovic thank you for your quick response!
I was indeed missing `expo-notifications` in my plugins config, unfortunately, even after adding it and making sure everything is configured as per `@allboatsrise/expo-marketingcloudsdk` documentation, I still get the same Error.

**Comment by byFadili** [comment]
Hi @andrejpavlovic 
Please let us know when will you be able to look at this.
Thank you!

**Comment by andrejpavlovic** [comment]
Not sure how you're building from Xcode - are you opening the workspace correctly (`ios/*.xcworkspace` file)?
This works just fine: `npx expo prebuild -p ios` and then `npx expo run:ios`
Also make sure your running latest Xcode maybe.

If it still doesn't work, start a new project using `npx create-expo-app my-app` and then try building with marketingcloudsdk.

**Comment by eridr** [comment]
I get the same error ass @byFadili `eas build --platform ios`

Log:
```swift
> 5 | #import <EXNotifications/EXNotificationCenterDelegate.h>
    |         ^ 'EXNotifications/EXNotificationCenterDelegate.h' file not found
  6 | #import <MarketingCloudSDK/MarketingCloudSDK.h>
  ```
  
Logs from `prebuild` generate:
  ```
  › Copying   expo-notifications EXNotifications/EXNotifications.framework/Headers/EXNotificationCenterDelegate.h ➜ node_modules/expo-notifications/ios/EXNotifications/Notifications/EXNotificationCenterDelegate.h
  ```
  
~~Perhaps the issue is that .h header file has been moved to a new folder?~~

Could it be related to `expo-notifications` being installed after `expo-marketingcloudsdk`?

**Comment by eridr** [comment]
> ...start a new project using `npx create-expo-app my-app` and then try building with marketingcloudsdk.

Verified, this works and build as expected.

**Comment by eridr** [comment]
@byFadili 

Adding `EXNotifications` in .podspec fix the issue.

```
s.dependency 'EXNotifications'
```

https://github.com/allboatsrise/expo-marketingcloudsdk/blob/develop/ios/ExpoMarketingCloudSdk.podspec

**Comment by byFadili** [comment]
> Verified, this works and build as expected.

@eridr Thank you !
I also tried using the plugin on a newly created test project, Build was successful, but App crashed every time when started on an iOS simulator.
I am using node 18 LTS by the way.

**Comment by byFadili** [comment]
> Adding EXNotifications in .podspec fix the issue.

@eridr after adding `s.dependency 'EXNotifications'` the `'EXNotifications/EXNotificationCenterDelegate.h' file not found` was kind of fixed (stopped appearing as an error) but the below error started showing up :
```bash
   6 |  */
   7 | 
>  8 | import ExpoModulesCore
     |        ^ could not find module 'ExpoModulesCore' for target 'x86_64-apple-ios-simulator'; found: arm64-apple-ios-simulator, at: /Users/Abdeljalil/Library/Developer/Xcode/DerivedData/EmCan-fbpdardzvbsxutfpcninpvezarbo/Build/Products/Debug-iphonesimulator/ExpoModulesCore/ExpoModulesCore.framework/Modules/ExpoModulesCore.swiftmodule
   9 | import ExpoMarketingCloudSdk
  10 | import ExpoClipboard
  11 | import EXConstants
```

**Comment by eridr** [comment]
@byFadili We did not replace `s.dependency 'EXNotifications'` with `s.dependency 'ExpoModulesCore'`?

**Comment by andrejpavlovic** [comment]
> > Verified, this works and build as expected.
> 
> @eridr Thank you ! I also tried using the plugin on a newly created test project, Build was successful, but App crashed every time when started on an iOS simulator. I am using node 18 LTS by the way.

You need to make sure you enter the correct values for appId, accessToken and serverUrl - especially serverUrl

**Comment by byFadili** [comment]
> @byFadili
> 
> Adding `EXNotifications` in .podspec fix the issue.
> 
> ```
> s.dependency 'EXNotifications'
> ```
> 
> https://github.com/allboatsrise/expo-marketingcloudsdk/blob/develop/ios/ExpoMarketingCloudSdk.podspec

This has fixed the issue on iOS for me, thank you !
